#!/bin/bash

# Unload nvidia modules
modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia

# Disable nVidia GPU
echo 'auto' > '/sys/bus/pci/devices/0000:01:00.0/power/control' | true
echo -n 1 > '/sys/bus/pci/devices/0000:01:00.0/remove' | true

# Disable nVidia HDMI audio
echo 'auto' > '/sys/bus/pci/devices/0000:01:00.1/power/control' | true
echo -n 1 > '/sys/bus/pci/devices/0000:01:00.1/remove' | true

